name: Robot Framework CI

on:
  push:
    branches: [ SauceDemo ]
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        rfbrowser init

    - name: Run Robot Tests (Pabot Parallel)
      run: |
        pabot --processes 4 --outputdir reports tests/

    - name: Upload Reports
      uses: actions/upload-artifact@v4
      with:
        name: robot-reports
        path: reports/